name: "Build on Ubuntu"
description: "Build the solutions on a Ubuntu container"
inputs:
  configuration:
    description: 'The build configuration to use'
    required: true
  solution:
    description: 'The solution that should be published'
    required: true
  dotnet_version:
    description: 'The dotnet version to use'
    required: true
runs:
  using: composite
  steps:

    # Setup .NET
    - name: 'Setup .NET'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    # Versioning.
    - name: 'Versioning'
      uses: dotnet/nbgv@master
      id: nbgv

    # Restore.
    - name: 'Restore dependencies'
      shell: pwsh
      run: >
        dotnet restore
        ${{ inputs.solution }}

    # Build.
    - name: 'Build'
      shell: pwsh
      run: >
        dotnet build
        ${{ inputs.solution }}
        --no-restore
        --configuration ${{ inputs.configuration }}
        /p:UbigiaIsRunningOnBuildAgent=true
        