name: "Publish NuGet"
description: "Create NuGet packages and publish them to nuget.org"

inputs:
  configuration:
    description: 'The build configuration to use'
    required: true
  nuget_org_xtechnology_token:
    description: 'The token needed to publish xTechnology packages to nuget.org'
    required: true
  nuget_org_ubigia_token:
    description: 'The token needed to publish Ubigia packages to nuget.org'
    required: true
  solution_file:
    description: 'The solution that should be published'
    required: true
  dotnet_version:
    description: 'The dotnet version to use'
    required: true
  nuget_ubigia_pack_filter:
    description: 'The filter for ubigia packages'
    required: true
  nuget_xtechnology_pack_filter:
    description: 'The filter for xtechnology packages'
    required: true
runs:
  using: composite
  steps:

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    # Versioning.
    - name: Versioning
      uses: dotnet/nbgv@master
      id: nbgv

    # Pack.
    - name: Pack NuGet packages
      shell: pwsh
      run: >
        dotnet pack
        "${{ inputs.solution_file }}"
        --configuration ${{ inputs.configuration }}
        --verbosity quiet
        /p:PackageVersion=${{ steps.nbgv.outputs.NuGetPackageVersion }}
        /p:RepositoryCommit=${{ steps.nbgv.outputs.GitCommitId }}
        /p:RepositoryType=git


    # Publish NuGet packages.
    - name: Publish EtAlii.xTechnology NuGet packages
      shell: pwsh
      run: >
        dotnet nuget push
        "${{ inputs.nuget_xtechnology_pack_filter }}"
        --skip-duplicate
        --api-key ${{ inputs.nuget_org_xtechnology_token }}
        --source https://api.nuget.org/v3/index.json

    - name: Publish EtAlii.Ubigia NuGet packages
      shell: pwsh
      run: >
        dotnet nuget push
        "${{ inputs.nuget_ubigia_pack_filter }}"
        --skip-duplicate
        --api-key ${{ inputs.nuget_org_ubigia_token }}
        --source https://api.nuget.org/v3/index.json
