name: "Test on Ubuntu"
description: "Test the solutions on a Ubuntu container"
inputs:
  configuration:
    description: 'The build configuration to use'
    required: false
    default: 'Release-Ubuntu'
runs:
  using: composite
  steps:

    # Setup .NET
    - name: 'Setup .NET'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.302

    - uses: actions/download-artifact@v2
      with:
        name: ubuntu-build

    - name: 'Configure shell to continue on error'
      shell: bash
      run: $ErrorActionPreference = "SilentlyContinue"

    - name: 'Test'
      shell: bash
      run: >
        dotnet test
        ./Source/EtAlii.Ubigia.sln
        --configuration ${{ inputs.configuration }}
        --no-build
        --verbosity normal
        --logger "trx;LogFileName=report.xunit.trx"
      #  -ErrorAction SilentlyContinue
      # run the next step even if this one step failed

    - name: 'Publish test results'
      uses: dorny/test-reporter@v1
      with:
        name: 'Test report (Ubuntu-latest)' # Name of the check run which will be created
        path: '**/*.trx'                    # Path to test results
        reporter: dotnet-trx                # Format of test results

