name: Build+Test

on:
  push:
    branches:
      - master
      - 'release/**'
    paths:
      - '!.github/workflows/**'
      - '.github/workflows/build+test.yml'

  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

      # Versioning.
    - name: Versioning
      uses: dotnet/nbgv@master
      id: nbgv

      # Restore, build and test.
    - name: Restore dependencies
      run: dotnet restore .\Source\EtAlii.Ubigia.sln

    - name: Build
      run: >
        dotnet build .\Source\EtAlii.Ubigia.sln
        --no-restore
        /p:UbigiaIsRunningOnBuildAgent=true

    - name: Test
      run: >
        dotnet test .\Source\EtAlii.Ubigia.sln
        --no-build
        --verbosity normal
