name: Build+Test

on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

      # Versioning.
    - name: Versioning
      uses: dotnet/nbgv@master

      # Restore, build and test.
    - name: Restore dependencies
      run: dotnet restore .\Source\EtAlii.Ubigia.sln
    - name: Build
      run: dotnet build --no-restore .\Source\EtAlii.Ubigia.sln /p:UbigiaIsRunningOnBuildAgent=true
    - name: Test
      run: dotnet test --no-build --verbosity normal .\Source\EtAlii.Ubigia.sln
