name: Build+test on Ubuntu

on:
  push:
    branches:
      - master
      - 'release/**'

  pull_request:
    branches: [ master ]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true   # Stop wasting time caching packages
  DOTNET_CLI_TELEMETRY_OPTOUT: true         # Disable sending usage data to Microsoft

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

      # Versioning.
    - name: Versioning
      uses: dotnet/nbgv@master
      id: nbgv

      # Restore, build and test.
    - name: Restore dependencies
      run: find ./Source -name '*.csproj' -not -name '*TrayIcon*' -exec dotnet restore {} \;

    - name: Build
      run: find ./Source -name '*.csproj' -not -name '*TrayIcon*' -exec dotnet build {} --no-restore /p:UbigiaIsRunningOnBuildAgent=true \;

    - name: Test
      run: find ./Source -name '*.csproj' -not -name '*TrayIcon*' -exec dotnet test {} --no-build --verbosity normal \;
