name: Build+test on Ubuntu

on:
  push:
    branches:
      - master
      - 'release/**'

  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

      # Versioning.
    - name: Versioning
      uses: dotnet/nbgv@master
      id: nbgv

      # Restore, build and test.
    - name: Restore dependencies
      run: >
        dotnet restore
        !*TrayIcon*.csproj


    - name: Build
      run: >
        dotnet build
        --no-restore
        /p:UbigiaIsRunningOnBuildAgent=true
        !*TrayIcon*.csproj

    - name: Test
      run: >
        dotnet test
        --no-build
        --verbosity normal
        !*TrayIcon*.csproj
