name: Build+test on Ubuntu

on:
  push:
    branches:
      - master
      - 'release/**'

  pull_request:
    branches: [ master ]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true   # Stop wasting time caching packages
  DOTNET_CLI_TELEMETRY_OPTOUT: true         # Disable sending usage data to Microsoft
  CONFIGURATION: 'Debug-Ubuntu'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

      # Versioning.
    - name: Versioning
      uses: dotnet/nbgv@master
      id: nbgv

      # Restore, build and test.
    - name: Restore dependencies
      run: >
      dotnet restore
      --configuration $CONFIGURATION
      ./Source/EtAlii.Ubigia.sln

    - name: Build
      run: >
      dotnet build
      ./Source/EtAlii.Ubigia.sln
      --configuration $CONFIGURATION
      --no-restore
      /p:UbigiaIsRunningOnBuildAgent=true

    - name: Test
      run: >
      dotnet test
      --configuration $CONFIGURATION
      --no-build
      --verbosity normal
      ./Source/EtAlii.Ubigia.sln
