name: Build+Test

on:
  push:
    branches:
      - master
      - 'release/**'

  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    #runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

      # Versioning.
    - name: Versioning
      uses: dotnet/nbgv@master
      id: nbgv

      # Restore, build and test.
    - name: Restore dependencies
      run: >
        dotnet restore
        ./Source/**/*.csproj;!**/EtAlii.xTechnology.Hosting.TrayIconHost.csproj;!**/EtAlii.xTechnology.Hosting.Tests.TrayIcon.csproj;!**/EtAlii.Ubigia.Infrastructure.Hosting.TrayIconHost.csproj


    # dotnet build ./Source/EtAlii.Ubigia.sln --no-restore /p:UbigiaIsRunningOnBuildAgent=true
    - name: Build
      run: >
        dotnet build
        --no-restore
        /p:UbigiaIsRunningOnBuildAgent=true
        ./Source/**/*.csproj;!**/EtAlii.xTechnology.Hosting.TrayIconHost.csproj;!**/EtAlii.xTechnology.Hosting.Tests.TrayIcon.csproj;!**/EtAlii.Ubigia.Infrastructure.Hosting.TrayIconHost.csproj

    - name: Test
      run: >
        dotnet test
        --no-build
        --verbosity normal
        ./Source/**/*.csproj;!**/EtAlii.xTechnology.Hosting.TrayIconHost.csproj;!**/EtAlii.xTechnology.Hosting.Tests.TrayIcon.csproj;!**/EtAlii.Ubigia.Infrastructure.Hosting.TrayIconHost.csproj

