name: Default workflow

on:
  push:
    branches:
      - master
      - 'release/**'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true   # Stop wasting time caching packages
  DOTNET_CLI_TELEMETRY_OPTOUT: true         # Disable sending usage data to Microsoft
  IMAGE_NAME: ubigia/storage
  UBIGIA_SOLUTION: .\Source\EtAlii.Ubigia.sln
  CONFIGURATION_WINDOWS: 'Release'
  CONFIGURATION_UBUNTU: 'Release-Ubuntu'
jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis - also needed by NBGV
      - name: Build on Ubuntu
        uses: ./.github/actions/build-ubuntu
        with:
          configuration: ${{ env.CONFIGURATION_UBUNTU }}

  build-on-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis - also needed by NBGV
      - name: Build on Windows
        uses: ./.github/actions/build-windows
        with:
          configuration: ${{ env.CONFIGURATION_WINDOWS }}

  test-on-ubuntu:
    runs-on: ubuntu-latest
    needs: build-on-ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis - also needed by NBGV
      - name: Test on Ubuntu
        uses: ./.github/actions/test-ubuntu
        with:
          configuration: ${{ env.CONFIGURATION_UBUNTU }}

  test-on-windows:
    runs-on: windows-latest
    needs: build-on-windows
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis - also needed by NBGV
      - name: Test on Windows
        uses: ./.github/actions/test-windows
        with:
          configuration: ${{ env.CONFIGURATION_WINDOWS }}

  sonarcloud-analysis:
    runs-on: windows-latest
    needs: build-on-windows
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis - also needed by NBGV
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
      - name: SonarCloud analysis
        uses: ./.github/actions/analyse-sonarcloud
        with:
          configuration: ${{ env.CONFIGURATION_WINDOWS }}

  codeql-analysis:
    runs-on: windows-latest
    needs: build-on-windows
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis - also needed by NBGV
      - name: CodeQL analysis
        uses: ./.github/actions/analyse-codeql
        with:
          configuration: ${{ env.CONFIGURATION_WINDOWS }}

  nuget-publish:
    runs-on: windows-latest
    needs: [codeql-analysis, sonarcloud-analysis, test-on-windows,  test-on-ubuntu]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis - also needed by NBGV
          nuget-org-xtechnology-token: ${{ secrets.NUGET_ORG_XTECHNOLOGY_TOKEN }}
          nuget-org-ubigia-token: ${{ secrets.NUGET_ORG_UBIGIA_TOKEN }}
      - name: Nuget publish
        uses: ./.github/actions/publish-nuget
        with:
          configuration: ${{ env.CONFIGURATION_WINDOWS }}

  docker-publish:
    runs-on: windows-latest
    needs: [codeql-analysis, sonarcloud-analysis, test-on-windows,  test-on-ubuntu]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis - also needed by NBGV
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerhub-user: ${{ secrets.DOCKERHUB_USER }}
      - name: Docker publish
        uses: ./.github/actions/publish-docker
        with:
          configuration: ${{ env.CONFIGURATION_WINDOWS }}
