name: Publish

on:
  workflow_dispatch:

jobs:
  publish:

    #runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore .\Source\EtAlii.Ubigia.sln
      - name: Build
        run: dotnet build --no-restore .\Source\EtAlii.Ubigia.sln
      - name: Test
        run: dotnet test --no-build --verbosity normal .\Source\EtAlii.Ubigia.sln
      - name: Pack
        run: dotnet pack --no-restore .\Source\EtAlii.Ubigia.sln
      - name: Publish EtAlii.xTechnology
        run: dotnet nuget push .\Source\**\EtAlii.xTechnology.*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_ORG_XTECHNOLOGY_TOKEN }} --source https://api.nuget.org/v3/index.json
      - name: Publish EtAlii.Ubigia
        run: dotnet nuget push .\Source\**\EtAlii.Ubigia.*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_ORG_UBIGIA_TOKEN }} --source https://api.nuget.org/v3/index.json

